# Generated by Django 2.2.5 on 2019-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='paysystem',
            field=models.ManyToManyField(blank=True, default='', null=True, to='bot.PaySystem'),
        ),
    ]
