# Generated by Django 2.2.5 on 2019-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('descriptionRU', models.TextField(verbose_name='Описание РУ')),
                ('descriptionUZ', models.TextField(verbose_name='Описание УЗ')),
                ('photoes', models.ManyToManyField(to='api.Photo')),
            ],
        ),
    ]
