# Generated by Django 2.2.6 on 2019-10-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='add',
            field=models.BooleanField(default=False, verbose_name='Дополнительная информация'),
        ),
    ]
